# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e9a04fc6f0a61abe3ee8a6e837f05cafb4bae09b6a8894009bf7f9f9764d52ed89ae81856a9d68cae12f42a1aca5191fa14f23a0724b4329c75de2560a675f3

test:
  secret_key_base: c9bf8e6e4d73156fcbb460a8fdbabbef131e0c091da9ba61df73ae0208e03af1a56242cf18c139dc6795e9f9e65dbf762c6a00a524d58d688b0956980031f2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
